image: node:carbon

variables:
  NODE_ENV: test
  CI: 'true'

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

# Without the `nice` command, `yarn install` will lock out completely the CI server.
before_script:
  - nice -n10 yarn install

# Tests Job
main_test:
  script:
    - yarn test --coverage
  # Source: 
  # https://github.com/Lingvokot/gitlab-ci-scripts/blob/master/README.md#unrelated-notes-on-gitlab-ci-setup
  coverage: '/All files(?:\s*\|\s*\d*\.?\d+\s*){3}\|\s*((\d*\.?\d+))\s*\|/'
  
  # Allows Downloading Jest's coverage reports after testing
  artifacts:
    name: '${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_report'
    expire_in: 1 week
    paths: 
      - coverage/lcov-report

