export const
    /** Colors */
    COLOR_PRIMARY = '#191c24',
    COLOR_PRIMARY_DARK = '#10121e',
    COLOR_ACCENT = '#ff4e64',
    COLOR_ACCENT_DARK = '#932d3a',
    COLOR_RED = "#ff4e64",
    COLOR_WHITE = '#FFFFFF',
    COLOR_GREY = '#bdc1c2',
    COLOR_WHITE_DARK = '#949494',
    COLOR_GOLD = '#f2b45c',
    COLOR_GOLD_LIGHT = '#ffe68b',
    COLOR_GOLD_DARK = '#bc842e',
    COLOR_WHITE_LIGHT = 'rgba(255, 255, 255, 0.6)',
    COLOR_DRAWER_BLACK = '#12151a',
    COLOR_BLACK = '#000000',
    COLOR_TRANSPARENT = 'rgba(0, 0, 0, 0)',

    /** Wallet login types **/
    LOGIN_PRIVATE_KEY = 0,
    LOGIN_MNEMONIC = 1,

    KEY_DOT = 10,
    KEY_ZERO = 11,
    KEY_BACKSPACE = 12,

    KEY_STRING_DOT = '.',
    KEY_STRING_ZERO = '0',
    KEY_STRING_BACKSPACE = 'Backspace',
    KEY_STRING_ENTER = 'Enter',

    PROVIDER_MAINNET_URL = 'https://mainnet.infura.io/',
    PROVIDER_DEV_URL = 'http://localhost:8545/',

    NETWORK_ID_MAINNET = '1',
    NETWORK_ID_DEV = '10',

    NETWORK_MAINNET = 'mainnet',
    NETWORK_DEV = 'dev',

    LS_KEY_SELECTED_TOKEN_CONTRACT = 'selectedTokenContract',

    TOKEN_TYPE_DBET_TOKEN_OLD = '0',
    TOKEN_TYPE_DBET_TOKEN_NEW = '1',

    DEFAULT_GAS_PRICE = '20',
    I18N_LANGUAGE_SET='I18N_LANGUAGE_SET',

    TYPE_HOUSE = '2',
    TYPE_HOUSE_AUTHORIZED_CONTROLLER = '3',
    TYPE_HOUSE_FUNDS_CONTROLLER = '4',
    TYPE_HOUSE_LOTTERY_CONTROLLER = '5',
    TYPE_HOUSE_SESSIONS_CONTROLLER = '6',
    TYPE_TEST_DECENT_BET_TOKEN = '7',

    CONTRACT_TYPES = [
        TOKEN_TYPE_DBET_TOKEN_OLD,
        TOKEN_TYPE_DBET_TOKEN_NEW,
        TYPE_HOUSE,
        TYPE_HOUSE_AUTHORIZED_CONTROLLER,
        TYPE_HOUSE_FUNDS_CONTROLLER,
        TYPE_HOUSE_LOTTERY_CONTROLLER,
        TYPE_HOUSE_SESSIONS_CONTROLLER,
        TYPE_TEST_DECENT_BET_TOKEN
    ]


